### PR TITLE
Added renderToFile and renderStringToFile to Template object.

### PR DESCRIPTION
**Pull request by thsteinmetz**
It might be useful to render a view/string to a file locally for things like PDF generation, static site generation, etc.

### CODE REVIEW

**Comment by thetutlage** [comment]
What’s the benefit of having it in the core?

**Comment by thsteinmetz** [comment]
Just a few less lines of code to write in application logic, really. Static
site generation and Html to PDF generation are two use cases I was thinking
of for it just living in core when I wrote it. If you don't see the
benefit, no worries.

**Comment by RomainLanz** [comment]
It's a useful feature for some use cases. Also, since it's a very small addition it will not be a pain to maintain if we add it to the core.

**Comment by thsteinmetz** [comment]
Closing PR.

**Pull request closed without merging**
